
jupyterlab:
  build: ./jupyterlab
  ports:
    - "8888:8888"
  volumes:
    - ./data:/opt/app/data
  entrypoint: sh -c 'jupyter lab --ip=* --port=8888 --no-browser --notebook-dir=/opt/app/data --allow-root'



selenium-hub:
  image: selenium/hub
  environment:
    - GRID_TIMEOUT=120
    - GRID_MAX_SESSION=200
    - GRID_NEW_SESSION_WAIT_TIMEOUT=-1
    - GRID_BROWSER_TIMEOUT=120
  ports:
    - "4444:4444"

chrome:
    image: selenium/node-chrome
    links:
      - selenium-hub:hub
    dns:
      - 8.8.8.8
      - 208.67.222.222
    environment:
      - NODE_MAX_INSTANCES=100
      - NODE_MAX_SESSION=100
    volumes:
      - /dev/shm:/dev/shm
    privileged: true

mitmproxy:
    image: mitmproxy/mitmproxy
    ports:
        - "8080:8080"
    expose:
        - "8080"
    stdin_open: true
    tty: true
    container_name: mitmproxy-container
